version: '3.4'
x-gpus: 1
services:
  jupyterlab:
    image: sensorium
    build:
      context: .
    volumes:
      - .:/project
      - ./notebooks:/notebooks
    environment:
      - JUPYTER_PASSWORD=
      - NVIDIA_VISIBLE_DEVICES=0

